### ISSUE TITLE
NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent

### ISSUE THREAD

**Issue by fantahund** [magmafoundation/Magma-1.18.x#8]
**Minecraft Version:** 1.18.2

**Forge Version:** 40.0.44

**Steps to Reproduce:**
 1. Put LogBlock in Plugin folder
 2. Start Server

`[13Apr.2022 00:54:16.090] [Server thread/ERROR] [org.bukkit.craftbukkit.v1_18_R2.CraftServer/]: net/md_5/bungee/api/chat/BaseComponent initializing LogBlock v1.17.0.0-SNAPSHOT (manually compiled) (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
	at de.diddiz.LogBlock.LogBlock.onLoad(LogBlock.java:65) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:325) ~[forge-1.18.2-40.0.44-universal.jar%23118!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:223) ~[server-1.18.2-20220404.173914-srg.jar%23114!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:692) ~[server-1.18.2-20220404.173914-srg.jar%23114!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:237) ~[server-1.18.2-20220404.173914-srg.jar%23114!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[forge-1.18.2-40.0.44-universal.jar%23118!/:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[forge-1.18.2-40.0.44-universal.jar%23118!/:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 6 more`

**Comment by fantahund** [comment]
I have the same problem with several plugins. ^^
